name: URL Test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install html2text
      run: sudo apt-get install -y html2text
    - name: URL Test
      run: ./test.sh
