apiVersion: v1
kind: Pod
metadata:
  name: helloworld-tomcat
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-demo
    image: zshaik/tomcat-funny-gif
    ports:
    - name: tomcat-port
      containerPort: 8080
